.TH "BasicHelloServer::BasicHello" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BasicHelloServer::BasicHello \- A basic hello class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BasicHello\&.h>\fP
.PP
Inherits \fBBasicHelloServer::ConfigurationInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBasicHello\fP ()"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fB~BasicHello\fP () override"
.br
.RI "Destructor\&. "
.ti -1c
.RI "void \fBreceiveData\fP (void *dataIn) override"
.br
.RI "receives data "
.ti -1c
.RI "void * \fBsendData\fP () override"
.br
.RI "sends the desired response "
.ti -1c
.RI "void \fBsetResponse\fP (const char *data)"
.br
.RI "Sets the internal response string\&. "
.in -1c
.SH "Detailed Description"
.PP 
A basic hello class\&. 

Receives and sends hello or goodbye 
.PP
Definition at line 25 of file BasicHello\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void BasicHelloServer::BasicHello::receiveData (void * dataIn)\fC [override]\fP, \fC [virtual]\fP"

.PP
receives data decodes the data and passes it to setResponse
.PP
\fBParameters:\fP
.RS 4
\fIdataIn\fP Recieves and decodes the data
.RE
.PP
\fBReturns:\fP
.RS 4
None 
.RE
.PP

.PP
Implements \fBBasicHelloServer::ConfigurationInterface\fP\&.
.PP
Definition at line 50 of file BasicHello\&.cpp\&.
.SS "void * BasicHelloServer::BasicHello::sendData ()\fC [override]\fP, \fC [virtual]\fP"

.PP
sends the desired response Returns the response\&.
.PP
\fBReturns:\fP
.RS 4
Void pointer to the response 
.RE
.PP

.PP
Implements \fBBasicHelloServer::ConfigurationInterface\fP\&.
.PP
Definition at line 62 of file BasicHello\&.cpp\&.
.SS "void BasicHelloServer::BasicHello::setResponse (const char * data)"

.PP
Sets the internal response string\&. Sets the response\&.
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP A pointer to the data
.RE
.PP
\fBReturns:\fP
.RS 4
None 
.RE
.PP

.PP
Definition at line 27 of file BasicHello\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
