.TH "cFunctions::cStdLib" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cFunctions::cStdLib \- Class header for stdlib wrapper\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cStdLib\&.h>\fP
.PP
Inherits \fBcFunctions::I_cStdLib\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void * \fBmalloc\fP (size_t __size) override"
.br
.RI "man 3 malloc "
.ti -1c
.RI "int \fBabs\fP (int j) override"
.br
.RI "man 3 abs "
.ti -1c
.RI "ldiv_t \fBldiv\fP (long numerator, long denominator) override"
.br
.RI "man 3 ldiv "
.in -1c
.SH "Detailed Description"
.PP 
Class header for stdlib wrapper\&. 
.PP
Definition at line 18 of file cStdLib\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
