.TH "cFunctions::cStdio" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cFunctions::cStdio
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcFunctions::I_cStdio\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBsnprintf\fP (char *str, size_t size, const char *format,\&.\&.\&.) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file cStdio\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "int cFunctions::cStdio::snprintf (char * str, size_t size, const char * format,  \&.\&.\&.)\fC [override]\fP, \fC [virtual]\fP"
man 3 printf 
.PP
Implements \fBcFunctions::I_cStdio\fP\&.
.PP
Definition at line 18 of file cStdio\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
