.TH "cFunctions::I_cStdio" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cFunctions::I_cStdio
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBcFunctions::cStdio\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBsnprintf\fP (char *str, size_t size, const char *format,\&.\&.\&.)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file I_cStdio\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual int cFunctions::I_cStdio::snprintf (char * str, size_t size, const char * format,  \&.\&.\&.)\fC [pure virtual]\fP"
man 3 printf 
.PP
Implemented in \fBcFunctions::cStdio\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
