.TH "cFunctions::I_cStdLib" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cFunctions::I_cStdLib \- cstdlib interface for mocking  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <I_cStdLib\&.h>\fP
.PP
Inherited by \fBcFunctions::cStdLib\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void * \fBmalloc\fP (size_t size)=0"
.br
.RI "man 3 malloc "
.ti -1c
.RI "virtual int \fBabs\fP (int j)=0"
.br
.RI "man 3 abs "
.ti -1c
.RI "virtual ldiv_t \fBldiv\fP (long numerator, long denominator)=0"
.br
.RI "man 3 ldiv "
.in -1c
.SH "Detailed Description"
.PP 
cstdlib interface for mocking 
.PP
Definition at line 18 of file I_cStdLib\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
