.TH "DUTTY" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DUTTY \- Functions as a simple manual verification of the testanalyser library soI can mvoe on\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Functions as a simple manual verification of the testanalyser library soI can mvoe on\&. 


.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
12/01/19 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
