.TH "hmarcks" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hmarcks \- Defines an abstraction for the dllOpening using dlfcn\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Defines an abstraction for the dllOpening using dlfcn\&. 


.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
23/03/19 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
