.TH "LoadDLL" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoadDLL
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBinterface\fP * \fBgetIF\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file LoadDll\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
