.TH "Logger" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Logger \- LogHandling class\&. Used for all/most Logs\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
LogHandling class\&. Used for all/most Logs\&. 

Represents a Single log file that can be written to\&.
.PP
Will handle different logs and their respective threads
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
12/08/18
.RE
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
13/08/18 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
