.TH "LoggerClass" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoggerClass \- Interface for logger class\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Interface for logger class\&. 


.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
05 Jul 2018 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
