.TH "LoggerClasses" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoggerClasses \- Pure interface for the logger strategy\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBI_LogFile\fP"
.br
.ti -1c
.RI "class \fBI_LogHandler\fP"
.br
.ti -1c
.RI "class \fBI_LogStrategy\fP"
.br
.ti -1c
.RI "class \fBlog_logIDMinusOne\fP"
.br
.ti -1c
.RI "class \fBlog_mapOutOfBounds\fP"
.br
.ti -1c
.RI "class \fBLogFile\fP"
.br
.ti -1c
.RI "class \fBloggerException\fP"
.br
.ti -1c
.RI "class \fBLogHandler\fP"
.br
.ti -1c
.RI "class \fBLogHandlerStrategy\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBStrategyEnums\fP : short { \fBSTDOUT\fP, \fBSTDERR\fP, \fBFSTREAM\fP, \fBSSTREAM\fP }"
.br
.ti -1c
.RI "enum \fBlogLevel\fP : char { \fBERROR\fP, \fBWARNING\fP, \fBINFO\fP, \fBDEBUG\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Pure interface for the logger strategy\&. 

Implemenation for the \fBLogHandlerStrategy\fP class\&.
.PP
Defines exceptions to be used by the logger\&.
.PP
Things used by too much to give to a specific class\&.
.PP
It's purpose is to provide concreticity to an ostream object that can then be passed into a logFile class
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
28/08/18 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
