.TH "logger" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logger \- Decides the strategy of the loghandler, implemented mainly, for now, for testing purposes\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Decides the strategy of the loghandler, implemented mainly, for now, for testing purposes\&. 


.PP
\fBDate:\fP
.RS 4
28/08/18
.RE
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBTodo\fP
.RS 4
Add register method So that users can add their own handling strategy 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
