.TH "md_Journal" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_Journal \- Journal 
This file was started as a way to collate my thoughts once my final year began and I had more things to worry/ think about\&.
.PP
\fIOctober 1st 2018\fP
.PP
>Today was mostly spent trying to remember how my testcase parser worked because I foolishly didn't bother to comment anything\&. So I'm still doing that currently 
