.TH "md_myLibraries_helloWorldProtocol_README" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_myLibraries_helloWorldProtocol_README \- README 
#Library: HelloWorldProtocol
.PP
\fBDescription\fP
.PP
This library is the mains et of classes used for the helloworld server app\&. It provides a very simpel interface for testing 'in and outs' without having to create a large and complicated plugin for testing\&.
.PP
\fBGotchas\fP
.PP
\fBHow to use\fP
.PP
\fBMethod\fP 
