.TH "md_myLibraries_gRPCInterface_README" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_myLibraries_gRPCInterface_README \- README 
#Library: gRPCInterface
.PP
\fBDescription\fP
.PP
This library will handle the API interface between gRPC requests, and managing the program\&.
.PP
\fBGotchas\fP
.PP
\fBHow to use\fP
.PP
\fBMethod\fP 
