.TH "md_myLibraries_freeFunctionsAndWrappers_README" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_myLibraries_freeFunctionsAndWrappers_README \- README 
#Library: Free Functions And Wrappers
.PP
\fBDescription\fP
.PP
Wraps any standalone functions into their own class to make mocking and unit testing more possible\&.
.PP
\fBGotchas\fP
.PP
\fBHow to use\fP
.PP
\fBMethod\fP 
