.TH "md_myLibraries_safeContainers_README" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_myLibraries_safeContainers_README \- README 
#Library: safeQueues
.PP
\fBDescription\fP
.PP
A header only library that implements a thread-safe queue for use in thread-boundaries for sending data and commands\&. Implemented using mutex locks\&. Will likely need improvement as optimizations demand it\&.
.PP
\fBGotchas\fP
.PP
\fBHow to use\fP
.PP
\fBMethod\fP 
