.TH "md_myLibraries_threadPool_README" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_myLibraries_threadPool_README \- README 
#Library: threadPool
.PP
\fBDescription\fP Implements a thread pool that can be used to exactly limit how many concurrent threads can be running in the program at any one time\&.
.PP
\fBGotchas\fP
.PP
\fBHow to use\fP
.PP
After instantiation, each component that needs to spawn threads should be given a reference to the thread pool\&. The AddTaskToQueue method derives all parameters and return types at compile time\&. The task is then added to a queue and will eventually be picked up by any free threads\&.
.PP
\fBMethod\fP 
