.TH "md_myLibraries_database_README" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_myLibraries_database_README \- Library: database 
\fBDecription\fP
.PP
This library will act as a simple database interface for a database that will be connected to the software\&. It will be relatively agnostic of the library that it is connected to\&.
.PP
It will run in its own thread and likely do little more than provide and interface for writing to and from the library\&. Other than potentially loading some running values from the database as a way to keep track between launches
.PP
\fBGotchas\fP
.PP
\fBHow to use\fP
.PP
\fBMethod\fP 
