.TH "md_myLibraries_testCaseAnalyser_README" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_myLibraries_testCaseAnalyser_README \- README 
#Library: testCaseAnalyser
.PP
\fBDescription\fP
.PP
uses rapidxml to lex an xml file, then gradually builds control objects that are needed by the protocol to create and read messages along with configuration objects that will configure the tests max/min states\&.
.PP
\fBGotchas\fP
.PP
\fBHow to use\fP
.PP
\fBMethod\fP 
