.TH "md_myLibraries_utility_README" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_myLibraries_utility_README \- README 
#Library: utilityFunctions
.PP
\fBDescription\fP
.PP
Just a collection of random utility functions that don't really belong to any specific class but have more uses than exclusively within where they were dreamed up\&.
.PP
\fBGotchas\fP
.PP
\fBHow to use\fP
.PP
\fBMethod\fP 
