.TH "md_myLibraries_timeTicker_README" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_myLibraries_timeTicker_README \- README 
#Library: timeTicker
.PP
\fBDescription\fP
.PP
Handles getting timestamps from either a timespec or timeval implementation\&.
.PP
\fBGotchas\fP
.PP
\fBHow to use\fP
.PP
\fBMethod\fP 
