.TH "NetworkCommunication" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NetworkCommunication \- NetworkCommunication Interface Class\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
NetworkCommunication Interface Class\&. 

Handles communication\&.
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
24/12/2018
.RE
.PP
Deals with outgoing and incoming communication and passes the information to whatever requires it
.PP
\fBDate:\fP
.RS 4
March 2018
.RE
.PP
Deals with outgoing and incoming communication and passes the information to whatever requires it
.PP
\fBDate:\fP
.RS 4
March 2018
.RE
.PP
\fBTodo\fP
.RS 4
perror needs changing to try catch blocks the use strerror 
.PP
refactor out setInterface\&. Do it in the constructor 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
