.TH "PluginLoader::PluginLoader" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PluginLoader::PluginLoader
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPluginLoader::I_PluginLoader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBScanForAllPluginsDefaultLoc\fP () override"
.br
.RI "Scans for all plugins in the default provided location\&. "
.ti -1c
.RI "bool \fBScanForAllPluginsNewLoc\fP (std::string const &pathToPlugins) override"
.br
.RI "Scans for all plugins in the location provided in pathToPlugins\&. "
.ti -1c
.RI "void \fBScanForComms\fP (std::string const &pathToPlugins) override"
.br
.RI "Scans for communication plugins in the provided folder + 'comms'\&. "
.ti -1c
.RI "void \fBScanForProtocols\fP (std::string const &pathToPlugins) override"
.br
.ti -1c
.RI "\fBsharedMap_t\fP< \fBCommunication::I_communication\fP > & \fBgetCommsPlugins\fP ()"
.br
.ti -1c
.RI "\fBsharedMap_t\fP< \fBProtocol::I_protocolInterface\fP > & \fBgetProtocolPlugins\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file pluginLoader\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool PluginLoader::PluginLoader::ScanForAllPluginsDefaultLoc ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Scans for all plugins in the default provided location\&. 
.PP
\fBTodo\fP
.RS 4
Flesh out return 
.RE
.PP
\fBReturns:\fP
.RS 4
true on success, otherwise false 
.RE
.PP

.PP
Implements \fBPluginLoader::I_PluginLoader\fP\&.
.PP
Definition at line 26 of file pluginLoader\&.cpp\&.
.SS "bool PluginLoader::PluginLoader::ScanForAllPluginsNewLoc (std::string const & pathToPlugins)\fC [override]\fP, \fC [virtual]\fP"

.PP
Scans for all plugins in the location provided in pathToPlugins\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpathToPlugins\fP The path to where to search for plugins 
.RE
.PP
\fBReturns:\fP
.RS 4
true on success, otherwise false 
.RE
.PP

.PP
Implements \fBPluginLoader::I_PluginLoader\fP\&.
.PP
Definition at line 38 of file pluginLoader\&.cpp\&.
.SS "void PluginLoader::PluginLoader::ScanForComms (std::string const & pathToPlugins)\fC [override]\fP, \fC [virtual]\fP"

.PP
Scans for communication plugins in the provided folder + 'comms'\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpathToPlugins\fP The path one above where the comms are located 
.RE
.PP

.PP
Implements \fBPluginLoader::I_PluginLoader\fP\&.
.PP
Definition at line 49 of file pluginLoader\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
