.TH "PluginLoader::I_Plugin" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PluginLoader::I_Plugin \- Top-level base class the plugin interfaces should derive from\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <I_plugin\&.h>\fP
.PP
Inherited by \fBCommunication::I_communication\fP, and \fBProtocol::I_protocolInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~I_Plugin\fP ()=default"
.br
.RI "Destructor\&. "
.ti -1c
.RI "virtual const char * \fBgetPluginName\fP ()=0"
.br
.RI "Returns the plugins name\&. "
.ti -1c
.RI "virtual const char * \fBgetPluginVersion\fP ()=0"
.br
.RI "Returns the version of the plugin\&. "
.ti -1c
.RI "virtual \fBPluginLoader::PLUGINTYPE_t\fP \fBgetPluginType\fP ()=0"
.br
.RI "Returns the plugin \fItype\fP "
.in -1c
.SH "Detailed Description"
.PP 
Top-level base class the plugin interfaces should derive from\&. 


.PP
\fBTemplate Parameters:\fP
.RS 4
\fIIFType\fP The interface type that we want to make a plugin for 
.RE
.PP

.PP
Definition at line 23 of file I_plugin\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual const char* PluginLoader::I_Plugin::getPluginName ()\fC [pure virtual]\fP"

.PP
Returns the plugins name\&. 
.PP
\fBReturns:\fP
.RS 4
The name of the plugin (as a const char*) 
.RE
.PP

.PP
Implemented in \fBCommunication::I_communication\fP, \fBProtocol::I_protocolInterface\fP, \fBlibNetworkCommunication::libNetworkCommunication\fP, \fBhwProt::HelloWorldProtocol\fP, and \fBlibNetworkCommunication::I_libNetworkCommunication\fP\&.
.SS "virtual \fBPluginLoader::PLUGINTYPE_t\fP PluginLoader::I_Plugin::getPluginType ()\fC [pure virtual]\fP"

.PP
Returns the plugin \fItype\fP 
.PP
\fBReturns:\fP
.RS 4
The the plugin is (as an enum) 
.RE
.PP

.PP
Implemented in \fBCommunication::I_communication\fP, \fBProtocol::I_protocolInterface\fP, \fBlibNetworkCommunication::libNetworkCommunication\fP, \fBhwProt::HelloWorldProtocol\fP, and \fBlibNetworkCommunication::I_libNetworkCommunication\fP\&.
.SS "virtual const char* PluginLoader::I_Plugin::getPluginVersion ()\fC [pure virtual]\fP"

.PP
Returns the version of the plugin\&. 
.PP
\fBReturns:\fP
.RS 4
The plugin version 
.RE
.PP

.PP
Implemented in \fBCommunication::I_communication\fP, \fBProtocol::I_protocolInterface\fP, \fBlibNetworkCommunication::libNetworkCommunication\fP, \fBhwProt::HelloWorldProtocol\fP, and \fBlibNetworkCommunication::I_libNetworkCommunication\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
