.TH "PluginLoader::dllAbstract< T >" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PluginLoader::dllAbstract< T > \- Class that hides the ugly dlfcn functions\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dllAbstract\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdllAbstract\fP (std::string path)"
.br
.RI "Constructor, comforms to RAiI\&. "
.ti -1c
.RI "\fB~dllAbstract\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "std::shared_ptr< T > \fBGetPluginFactory\fP ()"
.br
.RI "Returns a pointer to the factory function\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class PluginLoader::dllAbstract< T >"
Class that hides the ugly dlfcn functions\&. 
.PP
Definition at line 25 of file dllAbstract\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBPluginLoader::dllAbstract\fP< T >::\fBdllAbstract\fP (std::string path)\fC [inline]\fP"

.PP
Constructor, comforms to RAiI\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The path to the dll 
.RE
.PP

.PP
Definition at line 32 of file dllAbstract\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> std::shared_ptr<T> \fBPluginLoader::dllAbstract\fP< T >::GetPluginFactory ()\fC [inline]\fP"

.PP
Returns a pointer to the factory function\&. 
.PP
\fBReturns:\fP
.RS 4
A pointer to a function 
.RE
.PP

.PP
Definition at line 51 of file dllAbstract\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
