.TH "Plugin" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Plugin \- The \fBPluginLoader\fP interface\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
The \fBPluginLoader\fP interface\&. 

Class specifically for loading the communications plugins\&.
.PP
Exceptions for the pluginloader class\&.
.PP
Defines how the plugin loader will behave\&.
.PP
Where we store the plugin once it's initial functions have been loaded/mapped\&.
.PP
Common definitions used in the plugin loader\&.
.PP
Finds, stores and provides available plugins fo ruse throughout the system Should track: Communication plugins (networks, hardware, USB, etc)
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
March 2018
.RE
.PP
\fBTodo\fP
.RS 4
Protocol plugins (SNTP, LDAP, etc) 
.PP
threadHandler plugins (Changes the branching implementation) 
.PP
testCase plugins (Changes to how the testcases are read and handled?)
.RE
.PP
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
24/12/18
.RE
.PP
\fBTodo\fP
.RS 4
Add plugin support fo changing the branching method 
.RE
.PP
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
24/12/18
.RE
.PP
\fBTodo\fP
.RS 4
Move the ptr functions to their own file or smth 
.PP
Move the shareMap_t to its own file 
.RE
.PP
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
24/12/18
.RE
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
23/03/19
.RE
.PP
The implementations are below the class\&. The source file exclusively contains specializations for the templates according to the plugin type being loaded
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
24/12/18 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
