.TH "PluginLoader::Plugin_S< TypeToReturn >" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PluginLoader::Plugin_S< TypeToReturn >
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::function< const char *()> \fB_getPluginName\fP"
.br
.ti -1c
.RI "std::function< const char *()> \fB_getPluginVersion\fP"
.br
.ti -1c
.RI "std::function< \fBPLUGINTYPE_t\fP()> \fB_getPluginType\fP"
.br
.ti -1c
.RI "std::shared_ptr< TypeToReturn > \fB_newPlugin\fP"
.br
.ti -1c
.RI "void * \fB_libHandle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class TypeToReturn>
.br
struct PluginLoader::Plugin_S< TypeToReturn >"

.PP
Definition at line 22 of file pluginS\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
