.TH "PluginLoader::PluginLoaderTemplate< TpluginType >" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PluginLoader::PluginLoaderTemplate< TpluginType > \- Class that loads the plugins we want for the desired area\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pluginLoaderTemplate\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPluginLoaderTemplate\fP (std::string const &prefix, std::string const &qualifier, \fBsharedMap_t\fP< TpluginType > &plugins)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fB~PluginLoaderTemplate\fP ()=default"
.br
.RI "Default Destructor\&. "
.ti -1c
.RI "void \fBScanForPlugins\fP ()"
.br
.RI "Scans for plugins in location pointed to by _fullPath\&. "
.ti -1c
.RI "void \fBScanForPlugins\fP (std::string newDir)"
.br
.RI "Scans for plugins in the provided location\&. "
.ti -1c
.RI "\fBsharedMap_t\fP< TpluginType > \fBgetPlugins\fP ()"
.br
.RI "Gets the held plugin list\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class TpluginType>
.br
class PluginLoader::PluginLoaderTemplate< TpluginType >"
Class that loads the plugins we want for the desired area\&. 


.PP
\fBTemplate Parameters:\fP
.RS 4
\fITpluginType\fP The plugin we wish to load
.RE
.PP
The template parameter can be one of: Communication::I_comunication \fBProtocol::I_protocolInterface\fP <>
.PP
\fBTodo\fP
.RS 4
the other interfaces 
.RE
.PP

.PP
Definition at line 48 of file pluginLoaderTemplate\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class TpluginType > \fBPluginLoader::PluginLoaderTemplate\fP< TpluginType >::\fBPluginLoaderTemplate\fP (std::string const & prefix, std::string const & qualifier, \fBsharedMap_t\fP< TpluginType > & plugins)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fI_prefix\fP The top level directory where plugins are stored (i\&.e\&. '/opt/ProtDev/Plugins') 
.br
\fI_qualifier\fP The folder the plugins are stored in (i\&.e\&. 'comms' or '') 
.RE
.PP

.PP
Definition at line 97 of file pluginLoaderTemplate\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class TpluginType > \fBsharedMap_t\fP< TpluginType > \fBPluginLoader::PluginLoaderTemplate\fP< TpluginType >::getPlugins ()"

.PP
Gets the held plugin list\&. 
.PP
\fBReturns:\fP
.RS 4
a sharedMap_t type 
.RE
.PP

.PP
Definition at line 157 of file pluginLoaderTemplate\&.h\&.
.SS "template<class TpluginType > void \fBPluginLoader::PluginLoaderTemplate\fP< TpluginType >::ScanForPlugins (std::string newDir)"

.PP
Scans for plugins in the provided location\&. 
.PP
\fBParameters:\fP
.RS 4
\fInewDir\fP The directory where it should search for plugins 
.RE
.PP

.PP
\fBTodo\fP
.RS 4
Not a directory\&. throw 
.RE
.PP

.PP
Definition at line 117 of file pluginLoaderTemplate\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
