.TH "PluginLoader::PluginException" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PluginLoader::PluginException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fButility::extraExceptionBase\fP\&.
.PP
Inherited by \fBPluginLoader::PluginFactoryNullException\fP, and \fBPluginLoader::PluginHandleNullException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPluginException\fP (char *dlError)"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 20 of file pluginLoader_exception\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
