.TH "PluginLoader::I_PluginLoader" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PluginLoader::I_PluginLoader
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPluginLoader::PluginLoader\fP, and \fBPluginLoader::ProtocolPluginHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBScanForAllPluginsDefaultLoc\fP ()=0"
.br
.ti -1c
.RI "virtual bool \fBScanForAllPluginsNewLoc\fP (std::string const &pathToPlugins)=0"
.br
.ti -1c
.RI "virtual void \fBScanForComms\fP (std::string const &pathToPlugins)=0"
.br
.ti -1c
.RI "virtual void \fBScanForProtocols\fP (std::string const &pathToPlugins)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file I_PluginLoader\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
