.TH "Protocol" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Protocol \- ProtocolInterface\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBhwProt\fP"
.br
.RI "\fBHelloWorldProtocol\fP\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPROTOCOLDEVELOPER_HELLOWORLDPROTOCOL_H\fP"
.br
.RI "HelloWorldProtocol\&. "
.in -1c
.SH "Detailed Description"
.PP 
ProtocolInterface\&. 

Defines the interface that will be instantiated for protocols to communicate with the core
.PP
THE WAY IT WORKS IS:
.PP
Test handler will request data generation from protocol Testcase will request data Testcase will pass data to comms ahndler to be sent Comms handler will pass information back to the test the test will pass it to the protocol to be decode (And it be returned) Finally the test will log what the result was
.PP
\fBDate:\fP
.RS 4
March 2018 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define PROTOCOLDEVELOPER_HELLOWORLDPROTOCOL_H"

.PP
HelloWorldProtocol\&. The HelloWorldProtocol data generation and decoder, decalration
.PP
\fBDate:\fP
.RS 4
March 2018 
.RE
.PP

.PP
Definition at line 16 of file HelloWorldProtocol\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
