.TH "Protocol::DataStruct" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Protocol::DataStruct \- struct that we may or may not use to pass around information  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <I_protocolInterface\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fB_data_p\fP"
.br
.RI "A pointer to the data\&. "
.ti -1c
.RI "size_t \fB_size\fP"
.br
.RI "The size of the data\&. "
.in -1c
.SH "Detailed Description"
.PP 
struct that we may or may not use to pass around information 
.PP
Definition at line 32 of file I_protocolInterface\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
