.TH "SafeContainers::safeList< T >" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SafeContainers::safeList< T > \- A thread safe queue\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <safeList\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::list< T >::iterator \fBiterator\fP"
.br
.ti -1c
.RI "typedef std::list< T >::const_iterator \fBconst_iterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsafeList\fP (std::shared_ptr< std::list< T >> list_in)"
.br
.ti -1c
.RI "void \fBpush_front\fP (const T &val)"
.br
.ti -1c
.RI "void \fBpush_front\fP (T &&val)"
.br
.ti -1c
.RI "void \fBpop_front\fP ()"
.br
.ti -1c
.RI "void \fBpush_back\fP (const T &val)"
.br
.ti -1c
.RI "void \fBpush_back\fP (T &&val)"
.br
.ti -1c
.RI "void \fBpop_back\fP ()"
.br
.ti -1c
.RI "T & \fBfront\fP ()"
.br
.ti -1c
.RI "T & \fBback\fP ()"
.br
.ti -1c
.RI "bool \fBempty\fP () noexcept"
.br
.ti -1c
.RI "size_t \fBsize\fP () noexcept"
.br
.ti -1c
.RI "size_t \fBmax_size\fP () noexcept"
.br
.ti -1c
.RI "void \fBmerge\fP (std::list< T > &x)"
.br
.ti -1c
.RI "void \fBmerge\fP (std::list< T > &&x)"
.br
.ti -1c
.RI "iterator \fBbegin\fP ()"
.br
.ti -1c
.RI "iterator \fBend\fP ()"
.br
.ti -1c
.RI "const_iterator \fBcbegin\fP ()"
.br
.ti -1c
.RI "const_iterator \fBcend\fP ()"
.br
.ti -1c
.RI "std::list< T > & \fBgetList\fP ()"
.br
.RI "Returns the underlying list container (for merging) "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class SafeContainers::safeList< T >"
A thread safe queue\&. 


.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type the list should take 
.RE
.PP

.PP
Definition at line 26 of file safeList\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> std::list<T>& \fBSafeContainers::safeList\fP< T >::getList ()\fC [inline]\fP"

.PP
Returns the underlying list container (for merging) 
.PP
\fBReturns:\fP
.RS 4
A reference to the underlying std::list 
.RE
.PP

.PP
Definition at line 143 of file safeList\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
