.TH "SafeContainers::MathsModule" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SafeContainers::MathsModule
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPerformAction\fP (std::string *value_in, std::string minValue_in, std::string maxValue_in, int action)"
.br
.RI "Performs an action on the provided value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file mathsModule\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
