.TH "testCaseHandler::operation" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testCaseHandler::operation
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtestCaseHandler::OpVarBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBoperation\fP (std::string operationName, std::string dataToActOn, std::string _valueToReach)"
.br
.ti -1c
.RI "std::string \fBgetOperationName\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 23 of file operation\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
