.TH "testCaseHandler::TestCaseParser" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testCaseHandler::TestCaseParser
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestCaseParser\fP (std::string testFileName)"
.br
.ti -1c
.RI "bool \fBMoveToNextEntry\fP ()"
.br
.RI "Moves to the next node\&. "
.ti -1c
.RI "void \fBGetCurrentEntryName\fP (std::string &entryName)"
.br
.RI "Returns the current Entry's Name\&. "
.ti -1c
.RI "bool \fBGetCurrentEntryAttribute\fP (std::string &attributeName, std::string &attributeValue)"
.br
.RI "Gets the current attribute values\&. "
.ti -1c
.RI "void \fBGetEntryData\fP (std::string &entryData)"
.br
.RI "Get free Data from entry\&. "
.ti -1c
.RI "rapidxml::node_type \fBGetEntryType\fP ()"
.br
.RI "Get the current node type\&. "
.ti -1c
.RI "bool \fBMoveToSibling\fP ()"
.br
.RI "Grabs the sibling and moves the current node onto the stack\&. "
.ti -1c
.RI "bool \fBMoveToNexTSibling\fP ()"
.br
.RI "Advances to the next sibling\&. "
.ti -1c
.RI "bool \fBDoneWithSibling\fP ()"
.br
.RI "Discards current node with previous node and pops off the stack\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file testCaseParser\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool testCaseHandler::TestCaseParser::GetCurrentEntryAttribute (std::string & attributeName, std::string & attributeValue)"

.PP
Gets the current attribute values\&. Cycles over the current entries attributes\&.
.PP
\fBParameters:\fP
.RS 4
\fIattributeName\fP A reference to where to store the attribute's name 
.br
\fIattributeValue\fP A reference to where to store the attribute's value 
.RE
.PP
\fBReturns:\fP
.RS 4
False if more attributes, otherwise true 
.RE
.PP

.PP
Definition at line 64 of file testCaseParser\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
