.TH "testAnalyser2::RapidAbstract" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testAnalyser2::RapidAbstract
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtestAnalyser2::I_RapidAbstract\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRapidAbstract\fP (std::string const &filePath)"
.br
.RI "Constructor\&. Sets up the document ready to be analysed\&. "
.ti -1c
.RI "\fB~RapidAbstract\fP () override"
.br
.RI "Destructor\&. "
.ti -1c
.RI "const char * \fBGetCurrentNodeName\fP () override"
.br
.RI "Gets the current node name\&. "
.ti -1c
.RI "bool \fBMoveToNextNode\fP () override"
.br
.RI "Moves to the next node (straight downly) "
.ti -1c
.RI "const char * \fBGetNodeValue\fP () override"
.br
.RI "Gets the Node's data (for a node_data type) "
.ti -1c
.RI "std::size_t \fBGetNodeValueSize\fP () override"
.br
.RI "Returns the size of the nodes value\&. "
.ti -1c
.RI "bool \fBMoveToChild\fP () override"
.br
.RI "Moves to the child node (diagonally) "
.ti -1c
.RI "void \fBExitChild\fP () override"
.br
.RI "Returns to the previous highest node\&. "
.ti -1c
.RI "bool \fBSelectAttribute\fP () override"
.br
.RI "Selects an attribute to start reading that\&. "
.ti -1c
.RI "bool \fBMoveToNextAttribute\fP () override"
.br
.RI "Gets the next attribute in a node\&. "
.ti -1c
.RI "const char * \fBGetAttributeName\fP () override"
.br
.RI "Gets the attribute's name\&. "
.ti -1c
.RI "const char * \fBGetAttributeValue\fP () override"
.br
.RI "Gets the attribute's value\&. "
.ti -1c
.RI "rapidxml::node_type \fBGetCurrentNodeType\fP () override"
.br
.RI "Returns the current node's type\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file rapidAbstract\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testAnalyser2::RapidAbstract::RapidAbstract (std::string const & filePath)\fC [explicit]\fP"

.PP
Constructor\&. Sets up the document ready to be analysed\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilePath\fP The path to the xml file 
.RE
.PP

.PP
Definition at line 20 of file rapidAbstract\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void testAnalyser2::RapidAbstract::ExitChild ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Returns to the previous highest node\&. Pops of the current node to return to the last highest node\&. 
.PP
Implements \fBtestAnalyser2::I_RapidAbstract\fP\&.
.PP
Definition at line 90 of file rapidAbstract\&.cpp\&.
.SS "const char * testAnalyser2::RapidAbstract::GetAttributeName ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Gets the attribute's name\&. 
.PP
\fBReturns:\fP
.RS 4
A char* containing the node name 
.RE
.PP

.PP
Implements \fBtestAnalyser2::I_RapidAbstract\fP\&.
.PP
Definition at line 153 of file rapidAbstract\&.cpp\&.
.SS "const char * testAnalyser2::RapidAbstract::GetAttributeValue ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Gets the attribute's value\&. 
.PP
\fBReturns:\fP
.RS 4
A char* containing the node name 
.RE
.PP

.PP
Implements \fBtestAnalyser2::I_RapidAbstract\fP\&.
.PP
Definition at line 166 of file rapidAbstract\&.cpp\&.
.SS "const char * testAnalyser2::RapidAbstract::GetCurrentNodeName ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Gets the current node name\&. 
.PP
\fBReturns:\fP
.RS 4
A char* containing the node name
.PP
A char* contianing the node name 
.RE
.PP

.PP
Implements \fBtestAnalyser2::I_RapidAbstract\fP\&.
.PP
Definition at line 46 of file rapidAbstract\&.cpp\&.
.SS "rapidxml::node_type testAnalyser2::RapidAbstract::GetCurrentNodeType ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Returns the current node's type\&. 
.PP
\fBReturns:\fP
.RS 4
The node type that we have encountered as a rapidxml::node_type::[type] 
.RE
.PP

.PP
Implements \fBtestAnalyser2::I_RapidAbstract\fP\&.
.PP
Definition at line 179 of file rapidAbstract\&.cpp\&.
.SS "const char * testAnalyser2::RapidAbstract::GetNodeValue ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Gets the Node's data (for a node_data type) 
.PP
\fBReturns:\fP
.RS 4
const char* containing the data
.PP
const char* containg the data 
.RE
.PP

.PP
Implements \fBtestAnalyser2::I_RapidAbstract\fP\&.
.PP
Definition at line 98 of file rapidAbstract\&.cpp\&.
.SS "std::size_t testAnalyser2::RapidAbstract::GetNodeValueSize ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Returns the size of the nodes value\&. Returns the size of the node's value\&.
.PP
\fBReturns:\fP
.RS 4
the size of the value in the node
.PP
The size of the value 
.RE
.PP

.PP
Implements \fBtestAnalyser2::I_RapidAbstract\fP\&.
.PP
Definition at line 106 of file rapidAbstract\&.cpp\&.
.SS "bool testAnalyser2::RapidAbstract::MoveToChild ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Moves to the child node (diagonally) Moves to the child node (diagonally)\&.
.PP
\fBReturns:\fP
.RS 4
true on success, otherwise false
.PP
true on success, otherwise false (no children or failure) 
.RE
.PP

.PP
Implements \fBtestAnalyser2::I_RapidAbstract\fP\&.
.PP
Definition at line 73 of file rapidAbstract\&.cpp\&.
.SS "bool testAnalyser2::RapidAbstract::MoveToNextAttribute ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Gets the next attribute in a node\&. Gets the next attribute in a node\&. Checks to make sure an attribute is selected\&. If null is found, resets the current attribute\&.
.PP
\fBReturns:\fP
.RS 4
true on success, otherwise false 
.RE
.PP

.PP
Implements \fBtestAnalyser2::I_RapidAbstract\fP\&.
.PP
Definition at line 133 of file rapidAbstract\&.cpp\&.
.SS "bool testAnalyser2::RapidAbstract::MoveToNextNode ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Moves to the next node (straight downly) Moves to the next available node\&.
.PP
\fBReturns:\fP
.RS 4
true on success, otherwise false
.PP
true for success, otherwise false 
.RE
.PP

.PP
Implements \fBtestAnalyser2::I_RapidAbstract\fP\&.
.PP
Definition at line 54 of file rapidAbstract\&.cpp\&.
.SS "bool testAnalyser2::RapidAbstract::SelectAttribute ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Selects an attribute to start reading that\&. 
.PP
\fBReturns:\fP
.RS 4
true on success, otherwise false 
.RE
.PP

.PP
Implements \fBtestAnalyser2::I_RapidAbstract\fP\&.
.PP
Definition at line 114 of file rapidAbstract\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
