.TH "testAnalyser2::dataPoint" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testAnalyser2::dataPoint \- The datapoint itself, with related information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dataPoint\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fB_dataPointString\fP"
.br
.ti -1c
.RI "std::vector< \fBtestVariable\fP > \fB_variables\fP"
.br
.ti -1c
.RI "std::vector< \fBtestOperation\fP > \fB_operations\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The datapoint itself, with related information\&. 
.PP
Definition at line 43 of file dataPoint\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBtestOperation\fP> testAnalyser2::dataPoint::_operations"
< The variables present in the datapoint 
.PP
Definition at line 47 of file dataPoint\&.h\&.
.SS "std::vector<\fBtestVariable\fP> testAnalyser2::dataPoint::_variables"
< The data point itself i\&.e\&. [LI][VN][Mode][Stratum] 
.PP
Definition at line 46 of file dataPoint\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
