.TH "testAnalyser2::testOperation" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testAnalyser2::testOperation \- An operation on a variable\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dataPoint\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fB_name\fP"
.br
.ti -1c
.RI "std::string \fB_storedIn\fP"
.br
.ti -1c
.RI "std::string \fB_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An operation on a variable\&. 
.PP
Definition at line 33 of file dataPoint\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string testAnalyser2::testOperation::_storedIn"
< The name of the operation 
.PP
Definition at line 36 of file dataPoint\&.h\&.
.SS "std::string testAnalyser2::testOperation::_value"
< What variable does this oepration act on 
.PP
Definition at line 37 of file dataPoint\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
