.TH "testCaseHandler::DataEmitter" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testCaseHandler::DataEmitter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataEmitter\fP ()"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fB~DataEmitter\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "void \fBRegisterDataPoint\fP (std::shared_ptr< \fBDataPoint\fP > newDataPoint)"
.br
.RI "Registers a new dataPoint\&. "
.ti -1c
.RI "std::shared_ptr< \fBDataPoint\fP > \fBAccessDataPoint\fP (int position)"
.br
.RI "Accesses a datapoint referenced by position\&. "
.ti -1c
.RI "int \fBgetNumberOfDataPoints\fP ()"
.br
.RI "Getter, _numberofDataPoints\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file dataEmitter\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "std::shared_ptr< \fBDataPoint\fP > testCaseHandler::DataEmitter::AccessDataPoint (int position)"

.PP
Accesses a datapoint referenced by position\&. 
.PP
\fBParameters:\fP
.RS 4
\fIposition\fP What dataPoint to access 
.RE
.PP
\fBReturns:\fP
.RS 4
A shared_ptr containing the dataPoint 
.RE
.PP

.PP
Definition at line 44 of file dataEmitter\&.cpp\&.
.SS "int testCaseHandler::DataEmitter::getNumberOfDataPoints ()"

.PP
Getter, _numberofDataPoints\&. 
.PP
\fBReturns:\fP
.RS 4
The number of registered data points 
.RE
.PP

.PP
Definition at line 52 of file dataEmitter\&.cpp\&.
.SS "void testCaseHandler::DataEmitter::RegisterDataPoint (std::shared_ptr< \fBDataPoint\fP > newDataPoint)"

.PP
Registers a new dataPoint\&. 
.PP
\fBParameters:\fP
.RS 4
\fInewDataPoint\fP A shared_ptr to the new datapoint 
.RE
.PP

.PP
Definition at line 34 of file dataEmitter\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
