.TH "TestRunner" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestRunner \- The individual test thread that will handle sending and sending/receiving data to/FROM the target\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
The individual test thread that will handle sending and sending/receiving data to/FROM the target\&. 

Header for a test thread\&. This is the thread that will actually be run by the program that will send data to the target\&.
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
16/01/19 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
