.TH "testAnalyser2::testConfiguration" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testAnalyser2::testConfiguration \- A configuration object used to configure tests appropriately\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <testConfiguration\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fB_testName\fP"
.br
.ti -1c
.RI "std::string \fB_protocol\fP"
.br
.ti -1c
.RI "std::string \fB_tps\fP"
.br
.ti -1c
.RI "std::string \fB_chaosMulti\fP"
.br
.ti -1c
.RI "std::string \fB_secondsDuration\fP"
.br
.ti -1c
.RI "std::string \fB_maxThreads\fP"
.br
.ti -1c
.RI "std::string \fB_threadsPerInter\fP"
.br
.ti -1c
.RI "std::string \fB_commsHandler\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A configuration object used to configure tests appropriately\&. 
.PP
Definition at line 22 of file testConfiguration\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
