.TH "testAnalyser2::analyserFileDoesntExist_Exception" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testAnalyser2::analyserFileDoesntExist_Exception \- An incorrect node/tag pair has been given\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <analysisException\&.h>\fP
.PP
Inherits \fBtestAnalyser2::parserExceptionBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBanalyserFileDoesntExist_Exception\fP (const char *info)"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fB_info\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An incorrect node/tag pair has been given\&. 
.PP
Definition at line 142 of file analysisException\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
