.TH "testAnalyser2::parserException" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testAnalyser2::parserException \- Handles exceptions in the initial parsing\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <analysisException\&.h>\fP
.PP
Inherits parse_error\&.
.SH "Detailed Description"
.PP 
Handles exceptions in the initial parsing\&. 
.PP
Definition at line 27 of file analysisException\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
