.TH "testCaseHandler::OpVarBase" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testCaseHandler::OpVarBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBtestCaseHandler::operation\fP, and \fBtestCaseHandler::variable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpVarBase\fP (std::string name, std::string specialization, std::string value)"
.br
.ti -1c
.RI "std::string \fBgetName\fP ()"
.br
.RI "Getter, _name\&. "
.ti -1c
.RI "std::string \fBgetValue\fP ()"
.br
.RI "Getter, _value\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "std::string \fB_getSpecialization\fP ()"
.br
.RI "Getter, _action\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file opVarBase\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string testCaseHandler::OpVarBase::_getSpecialization ()\fC [protected]\fP"

.PP
Getter, _action\&. 
.PP
\fBReturns:\fP
.RS 4
The specialization that this performs 
.RE
.PP

.PP
Definition at line 38 of file opVarBase\&.cpp\&.
.SS "std::string testCaseHandler::OpVarBase::getName ()"

.PP
Getter, _name\&. 
.PP
\fBReturns:\fP
.RS 4
The name of the entry 
.RE
.PP

.PP
Definition at line 30 of file opVarBase\&.cpp\&.
.SS "std::string testCaseHandler::OpVarBase::getValue ()"

.PP
Getter, _value\&. 
.PP
\fBReturns:\fP
.RS 4
The value needed 
.RE
.PP

.PP
Definition at line 46 of file opVarBase\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
