.TH "Test" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Test \- The test runner class itself\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
The test runner class itself\&. 

Implementation for the test runner\&. Sanitises the environment and kicks off the tests\&.
.PP
This class is responsible for setting up the test environment\&.
.PP
Grabs the required plugins from the directory pointed to\&. Creates the test objects Sorts out the thread handling/branching method Passes the test objects to where they are required Pre-creates some values ready to send Starts the test
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
13/01/19
.RE
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
13/01/19 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
