.TH "testAnalyser2" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testAnalyser2 \- Interface for the abstraction layer between an xml parser and the software\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Interface for the abstraction layer between an xml parser and the software\&. 

Builds the actual testfile object for use by the test threads\&.
.PP
Implementation for the testfile object builder\&.
.PP
Kicks off the analysis\&. Interacts with the user\&.
.PP
Provides an abstraction between rapidxml and the library\&. Improves EoU\&.
.PP
Handles exceptions in the parser\&. Improves hiding from rapidxml\&.
.PP
Represents the testfile itself and is passed/used by the test handler\&.
.PP
Represents a configuration object for configuring tests\&.
.PP
Represents a single data point\&.
.PP
Reads the testfile and stores it in configuration objects for configuration and reading\&.
.PP
Interface for the testAnalyser2 class\&.
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
12/01/19
.RE
.PP
\fBTodo\fP
.RS 4
rapidabstract interface 
.RE
.PP
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
12/01/19
.RE
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
02/01/19
.RE
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
03/01/19
.RE
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
03/01/19
.RE
.PP
\fBTodo\fP
.RS 4
Figure out how to collapse the where() from the rapidxml::parse_error into a single what() 
.RE
.PP
.PP
Acts as a 'context' for the xml document\&. Allows a user to more easily drill down\&. Access nodes, data, and values more directly and hides a lot of the messy types
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
02/01/19
.RE
.PP
\fBTodo\fP
.RS 4
rapidabstract interface 
.RE
.PP
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
03/01/19
.RE
.PP
\fBTodo\fP
.RS 4
Refactor variables and operations into their respective classes! 
.RE
.PP
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
03/01/19
.RE
.PP
\fBTodo\fP
.RS 4
rapidabstract interface 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
