.TH "TestRunner::TestThread" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestRunner::TestThread \- A single test thread\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <testThread\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestThread\fP (const \fButility::ThreadSafeT\fP< bool > &killThread_in, std::shared_ptr< \fBCommunication::I_communication\fP > &commsInterface_in, std::shared_ptr< \fBProtocol::I_protocolInterface\fP > &protocolInterface_in, \fBSafeContainers::safeList\fP< \fBProtocol::DataStruct\fP > &resultsList_in, \fBSafeContainers::safeList\fP< int > &codeList_in, long ratio_in)"
.br
.RI "Contructor\&. "
.ti -1c
.RI "\fB~TestThread\fP ()=default"
.br
.RI "Destructor\&. "
.ti -1c
.RI "void \fBStartTest\fP ()"
.br
.RI "Performs the test\&. "
.ti -1c
.RI "bool \fBGetFinished\fP ()"
.br
.RI "Returns whether or not the thread is finished (threadsafe) "
.ti -1c
.RI "void \fBSetFinished\fP (bool newVal)"
.br
.RI "Sets the internal finished boolean (threadsafe) "
.in -1c
.SH "Detailed Description"
.PP 
A single test thread\&. 
.PP
Definition at line 30 of file testThread\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TestRunner::TestThread::TestThread (const \fButility::ThreadSafeT\fP< bool > & killThread_in, std::shared_ptr< \fBCommunication::I_communication\fP > & commsInterface_in, std::shared_ptr< \fBProtocol::I_protocolInterface\fP > & protocolInterface_in, \fBSafeContainers::safeList\fP< \fBProtocol::DataStruct\fP > & resultsList_in, \fBSafeContainers::safeList\fP< int > & codeList_in, long ratio_in)"

.PP
Contructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIkillThread_in\fP A reference to the kill thread handler 
.br
\fIcommsInterface_in\fP The comms that we are interfacing over 
.br
\fIprotocolInterface_in\fP The protocol that we are using to generate data 
.br
\fIresultsList_in\fP Where to store the results 
.br
\fIratio_in\fP The rough gap between firings we want
.br
\fIkillThread_in\fP A reference to the kill thread handler 
.br
\fIcommsInterface_in\fP The comms that we are interfacing over 
.br
\fIprotocolInterface_in\fP The protocol that we are using to generate data 
.br
\fIresultsList_in\fP Where to store the results 
.br
\fIcodeList_in\fP Where to store resultant error codes 
.br
\fIratio_in\fP The rough gap between firings we want 
.RE
.PP

.PP
Definition at line 29 of file testThread\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool TestRunner::TestThread::GetFinished ()"

.PP
Returns whether or not the thread is finished (threadsafe) Returns whether or not the thread is finished\&.
.PP
\fBReturns:\fP
.RS 4
the internal finished boolean 
.RE
.PP

.PP
Definition at line 90 of file testThread\&.cpp\&.
.SS "void TestRunner::TestThread::SetFinished (bool newVal)"

.PP
Sets the internal finished boolean (threadsafe) 
.PP
\fBParameters:\fP
.RS 4
\fInewVal\fP What to set the finished boolean to 
.RE
.PP

.PP
Definition at line 98 of file testThread\&.cpp\&.
.SS "void TestRunner::TestThread::StartTest ()"

.PP
Performs the test\&. Starts the test thread running\&. @TODO: fix this 
.PP
Definition at line 47 of file testThread\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
