.TH "testAnalyser2::TestAnalyser2" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testAnalyser2::TestAnalyser2
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtestAnalyser2::I_TestAnalyser2\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestAnalyser2\fP (std::string &testfile)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fB~TestAnalyser2\fP ()=default"
.br
.RI "destructor "
.ti -1c
.RI "void \fBstartAnalysis\fP () override"
.br
.RI "Starts the testfile analysis\&. "
.ti -1c
.RI "\fBTestFile\fP & \fBGetTestFile\fP () override"
.br
.RI "Returns a reference to the testfile object (That's ready for use) "
.ti -1c
.RI "bool \fBisAnalysed\fP () override"
.br
.RI "Returns whether or not the testfile has been analysed yet\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file testAnalyser2\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testAnalyser2::TestAnalyser2::TestAnalyser2 (std::string & testfile)\fC [explicit]\fP"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fItestfile\fP The absolute location of the testfile 
.RE
.PP

.PP
Definition at line 23 of file testAnalyser2\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBTestFile\fP & testAnalyser2::TestAnalyser2::GetTestFile ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Returns a reference to the testfile object (That's ready for use) Returns the testfile (as long as it's completed)
.PP
\fBReturns:\fP
.RS 4
A Testfile reference
.PP
A reference to an analysed testfile\&. If not completed, testfile will be empty 
.RE
.PP

.PP
Implements \fBtestAnalyser2::I_TestAnalyser2\fP\&.
.PP
Definition at line 55 of file testAnalyser2\&.cpp\&.
.SS "bool testAnalyser2::TestAnalyser2::isAnalysed ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Returns whether or not the testfile has been analysed yet\&. Returns the analysed boolean, indicating whether or not the testfile has been analysed\&.
.PP
\fBReturns:\fP
.RS 4
true for analysed, otherwise false
.PP
true if analysed, otherwise false 
.RE
.PP

.PP
Implements \fBtestAnalyser2::I_TestAnalyser2\fP\&.
.PP
Definition at line 67 of file testAnalyser2\&.cpp\&.
.SS "void testAnalyser2::TestAnalyser2::startAnalysis ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Starts the testfile analysis\&. Begins the analysis of the testcase\&. 
.PP
Implements \fBtestAnalyser2::I_TestAnalyser2\fP\&.
.PP
Definition at line 34 of file testAnalyser2\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
