.TH "testAnalyser2::TestFile" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testAnalyser2::TestFile \- Object representation of a testfile\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <testFile\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBGetNumberOfDataPoints\fP ()"
.br
.RI "Returns the total number of datapoints\&. "
.ti -1c
.RI "\fBdataPoint\fP & \fBGetDataPoint\fP (int index)"
.br
.RI "Gets a specific datapoint\&. "
.ti -1c
.RI "std::vector< \fBdataPoint\fP > & \fBGetAllDataPoints\fP ()"
.br
.RI "Returns a reference to the vector containing all datapoints\&. "
.ti -1c
.RI "const \fBtestConfiguration\fP & \fBGetTestConfiguration\fP ()"
.br
.RI "Returns A const reference to the tests configuration information\&. "
.ti -1c
.RI "void \fBAddDataPoint\fP (\fBdataPoint\fP &newDP)"
.br
.RI "Adds a new datapoint to the testcase\&. "
.ti -1c
.RI "void \fBAddConfiguration\fP (\fBtestConfiguration\fP &newConf)"
.br
.RI "Adds the configuration to the testcase\&. "
.in -1c
.SH "Detailed Description"
.PP 
Object representation of a testfile\&. 
.PP
Definition at line 24 of file testFile\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void testAnalyser2::TestFile::AddConfiguration (\fBtestConfiguration\fP & newConf)"

.PP
Adds the configuration to the testcase\&. Adds a new testconfiguration to testfile representation\&.
.PP
\fBParameters:\fP
.RS 4
\fInewConf\fP The configuration we wish to add
.br
\fInewConf\fP A reference to the configuration 
.RE
.PP

.PP
Definition at line 60 of file testFile\&.cpp\&.
.SS "void testAnalyser2::TestFile::AddDataPoint (\fBdataPoint\fP & newDP)"

.PP
Adds a new datapoint to the testcase\&. Adds a new datapoint to the internal vector\&.
.PP
\fBParameters:\fP
.RS 4
\fInewDP\fP The new datapoint we wish to add
.br
\fInewDP\fP A reference to the new datapoint 
.RE
.PP

.PP
Definition at line 52 of file testFile\&.cpp\&.
.SS "std::vector< \fBdataPoint\fP > & testAnalyser2::TestFile::GetAllDataPoints ()"

.PP
Returns a reference to the vector containing all datapoints\&. Returns a reference to the entire datapoint object vector\&.
.PP
\fBReturns:\fP
.RS 4
A reference to the vector containing all data points
.PP
A reference to the entire datapoint object vector 
.RE
.PP

.PP
Definition at line 36 of file testFile\&.cpp\&.
.SS "\fBdataPoint\fP & testAnalyser2::TestFile::GetDataPoint (int index)"

.PP
Gets a specific datapoint\&. Returns a datapoint ref by the index it's stored at\&.
.PP
\fBParameters:\fP
.RS 4
\fIindex\fP Which datapoint to get 
.RE
.PP
\fBReturns:\fP
.RS 4
A reference to that datapoint
.RE
.PP
\fBParameters:\fP
.RS 4
\fIindex\fP Which datapoint we want 
.RE
.PP
\fBReturns:\fP
.RS 4
A datapoint reference 
.RE
.PP

.PP
Definition at line 28 of file testFile\&.cpp\&.
.SS "size_t testAnalyser2::TestFile::GetNumberOfDataPoints ()"

.PP
Returns the total number of datapoints\&. Returns the amount of data points present\&.
.PP
\fBReturns:\fP
.RS 4
The number of datapoints as a size_t
.PP
a size_t with the number of datapoints stored 
.RE
.PP

.PP
Definition at line 19 of file testFile\&.cpp\&.
.SS "const \fBtestConfiguration\fP & testAnalyser2::TestFile::GetTestConfiguration ()"

.PP
Returns A const reference to the tests configuration information\&. Returns a const ref to the testconfiguration data\&.
.PP
\fBReturns:\fP
.RS 4
A const ref to the object's Configuration data
.PP
A const ref to the testconfiguration data 
.RE
.PP

.PP
Definition at line 44 of file testFile\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
