.TH "Thread" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Thread \- Implements a thread pool queue for running tests against the comms handler\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Implements a thread pool queue for running tests against the comms handler\&. 

The thread worker that carries out tasks given to it\&.
.PP
\fBDate:\fP
.RS 4
20/05/2018
.PP
23/5/18 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
