.TH "ThreadHandler" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThreadHandler \- Interface Representing a single testThread for sending and receiving data\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Interface Representing a single testThread for sending and receiving data\&. 


.PP
\fBDate:\fP
.RS 4
17/05/18 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
