.TH "TimeTicker::TimeTicker" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimeTicker::TimeTicker
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTimeTicker::I_TimeTicker\fP\&.
.PP
Inherited by \fBTimeTicker::TimeSpec\fP, and \fBTimeTicker::TimeVal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const char * \fBgetTimeStampMicro\fP () override"
.br
.ti -1c
.RI "const char * \fBgetTimestampMilli\fP () override"
.br
.ti -1c
.RI "const char * \fBgetStringMicro\fP (const struct timeval *tv) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file timeTicker\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
