.TH "TimeTicker::XMLTime" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimeTicker::XMLTime
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "char * \fBgetXMLTimestamp\fP (time_t t, int components)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file xMLTime\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "char * TimeTicker::XMLTime::getXMLTimestamp (time_t t, int components)"
@TODO Finish classifying 
.PP
Definition at line 23 of file xMLTime\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
