.TH "timeSpec" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
timeSpec \- Implementation for all TimeSpec Related functions\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Implementation for all TimeSpec Related functions\&. 


.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
18/12/18 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
