.TH "TimeTicker::WallClock" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimeTicker::WallClock
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWallClock\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBWallClock\fP (std::unique_ptr< \fBI_gMTHandler\fP > gmtHandler, std::unique_ptr< \fBcFunctions::I_cStdio\fP > cstdioFunctions, std::unique_ptr< \fBcFunctions::I_cStdLib\fP > cstdlibFunctions)"
.br
.RI "Modular constructor, used to reaplce different std libraries\&. "
.ti -1c
.RI "const char * \fBgetTimeToString\fP (time_t theTime)"
.br
.RI "Returns the time as a string (seconds precision) "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file wallClock\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TimeTicker::WallClock::WallClock (std::unique_ptr< \fBI_gMTHandler\fP > gmtHandler, std::unique_ptr< \fBcFunctions::I_cStdio\fP > cstdioFunctions, std::unique_ptr< \fBcFunctions::I_cStdLib\fP > cstdlibFunctions)"

.PP
Modular constructor, used to reaplce different std libraries\&. 
.PP
\fBParameters:\fP
.RS 4
\fIgmtHandler\fP The gmtHandler 
.br
\fIcstdioFunctions\fP The stdio or equivalent functions 
.br
\fIcstdlibFunctions\fP The stdlib or equivalent functions 
.RE
.PP

.PP
Definition at line 34 of file wallClock\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "const char * TimeTicker::WallClock::getTimeToString (time_t theTime)"

.PP
Returns the time as a string (seconds precision) 
.PP
\fBParameters:\fP
.RS 4
\fItheTime\fP The time (in seconds) we wish to know 
.RE
.PP
\fBReturns:\fP
.RS 4
A Char* containing the timestamp 
.RE
.PP

.PP
Definition at line 47 of file wallClock\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
