.TH "TimeTicker::TimeVal" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimeTicker::TimeVal
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTimeTicker::TimeTicker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTimeVal\fP ()"
.br
.RI "Default Constructor\&. "
.ti -1c
.RI "\fBTimeVal\fP (std::unique_ptr< \fBI_gMTHandler\fP > gmtHandler, std::unique_ptr< \fBcFunctions::I_cStdio\fP > stdioModule)"
.br
.RI "Allows the underlying modules to be swapped out with something more non-standard\&. "
.ti -1c
.RI "const char * \fBgetTimeStampMicro\fP () override"
.br
.RI "Returns a char string containing a timestamp generated using struct timeval (Microsecond Precision) "
.ti -1c
.RI "const char * \fBgetTimestampMilli\fP () override"
.br
.RI "Returns a char string containing a timestamp generated using struct timeval (Millisecond Precision) "
.ti -1c
.RI "const char * \fBgetStringMicro\fP (const struct timeval *tv) override"
.br
.RI "Returns a char string containing a timestamp generated using struct timeval\&. "
.ti -1c
.RI "TTRetCode \fBPrintGeneralizedTime\fP (const TT_tm_t *tm_p, unsigned int *microsecs_p, unsigned int fractionDigits, char *buf_p, size_t bufSize)"
.br
.RI "Prints the time given in tm_p according to RFC 4517 (YYYYMMDDHHMMSS[\&.fff][Z|[+-]hhmm]) "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file timeVal\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TimeTicker::TimeVal::TimeVal (std::unique_ptr< \fBI_gMTHandler\fP > gmtHandler, std::unique_ptr< \fBcFunctions::I_cStdio\fP > stdioModule)"

.PP
Allows the underlying modules to be swapped out with something more non-standard\&. 
.PP
\fBParameters:\fP
.RS 4
\fIgmtHandler\fP The gmt Handler we wish to use 
.br
\fIstdioModule\fP The stdio module we wish to use 
.RE
.PP

.PP
Definition at line 36 of file timeVal\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "const char * TimeTicker::TimeVal::getStringMicro (const struct timeval * tv)\fC [override]\fP, \fC [virtual]\fP"

.PP
Returns a char string containing a timestamp generated using struct timeval\&. 
.PP
\fBParameters:\fP
.RS 4
\fItv\fP The timeval struct we wish to get the time for 
.RE
.PP
\fBReturns:\fP
.RS 4
The timestamp in YYYY-MM-DD HH:MM:SS\&.FFF[(+|-HHMM)|Z] 
.RE
.PP

.PP
Reimplemented from \fBTimeTicker::TimeTicker\fP\&.
.PP
Definition at line 77 of file timeVal\&.cpp\&.
.SS "const char * TimeTicker::TimeVal::getTimeStampMicro ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Returns a char string containing a timestamp generated using struct timeval (Microsecond Precision) 
.PP
\fBReturns:\fP
.RS 4
The timestamp in YYYY-MM-DD HH:MM:SS\&.FFF[(+|-HHMM)|Z] 
.RE
.PP

.PP
Reimplemented from \fBTimeTicker::TimeTicker\fP\&.
.PP
Definition at line 47 of file timeVal\&.cpp\&.
.SS "const char * TimeTicker::TimeVal::getTimestampMilli ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Returns a char string containing a timestamp generated using struct timeval (Millisecond Precision) 
.PP
\fBReturns:\fP
.RS 4
The timestamp in YYYY-MM-DD HH:MM:SS\&.FFF[(+|-HHMM)|Z] 
.RE
.PP

.PP
Reimplemented from \fBTimeTicker::TimeTicker\fP\&.
.PP
Definition at line 62 of file timeVal\&.cpp\&.
.SS "TTRetCode TimeTicker::TimeVal::PrintGeneralizedTime (const TT_tm_t * tm_p, unsigned int * microsecs_p, unsigned int fractionDigits, char * buf_p, size_t bufSize)"

.PP
Prints the time given in tm_p according to RFC 4517 (YYYYMMDDHHMMSS[\&.fff][Z|[+-]hhmm]) 
.PP
\fBParameters:\fP
.RS 4
\fItm_p\fP The tm struct we wish to use (that contains the time) 
.br
\fImicrosecs_p\fP Where the microseconds are located 
.br
\fIfractionDigits\fP How many places after the DP do we want 
.br
\fIbuf_p\fP Where to store the time stamp 
.br
\fIbufSize\fP How large is the buffer 
.RE
.PP
\fBReturns:\fP
.RS 4
false for failure, true on success 
.RE
.PP

.PP
Definition at line 154 of file timeVal\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
