.TH "TimeTicker::I_gMTHandler" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimeTicker::I_gMTHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBTimeTicker::GMTHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBPrintGMTOffset\fP (const struct tm *theTimeTM_p, char *buffer_p, size_t length) const =0"
.br
.ti -1c
.RI "virtual TTRetCode_E \fBGetGMTOffset\fP (const struct tm *tm_p, \fBTTGMTOffset_t\fP *offset_p) const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file I_gMTHandler\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
