.TH "TimeTicker::I_TimeTicker" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimeTicker::I_TimeTicker
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBTimeTicker::TimeTicker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual const char * \fBgetTimeStampMicro\fP ()=0"
.br
.ti -1c
.RI "virtual const char * \fBgetTimestampMilli\fP ()=0"
.br
.ti -1c
.RI "virtual const char * \fBgetStringMicro\fP (const struct timeval *tv)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file I_TimeTicker\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
