.TH "TTGMTOffset" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TTGMTOffset \- Structure to represent an offset from GMT\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <timeTickerCommon\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBhours\fP"
.br
.RI "Hour component of the GMT offset\&. "
.ti -1c
.RI "int \fBminutes\fP"
.br
.RI "Minute component of the GMT offset\&. "
.ti -1c
.RI "int \fBtotalSeconds\fP"
.br
.RI "Entire offset expressed as seconds\&. "
.in -1c
.SH "Detailed Description"
.PP 
Structure to represent an offset from GMT\&. 
.PP
Definition at line 53 of file timeTickerCommon\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
