.TH "utility::ThreadSafeT< T >" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utility::ThreadSafeT< T > \- Allows for basic thread safe access to some type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <threadSafeT\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThreadSafeT\fP (T initial)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fB~ThreadSafeT\fP ()=default"
.br
.RI "Destructor\&. "
.ti -1c
.RI "T \fBGetT\fP ()"
.br
.RI "Returns the internal T store\&. "
.ti -1c
.RI "void \fBSetT\fP (T newVal)"
.br
.RI "Sets the internal T variable\&. "
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.RI "Implicit conversion operator for easier use in ifs\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class utility::ThreadSafeT< T >"
Allows for basic thread safe access to some type\&. 


.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type the class should protect 
.RE
.PP

.PP
Definition at line 24 of file threadSafeT\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fButility::ThreadSafeT\fP< T >::\fBThreadSafeT\fP (T initial)\fC [inline]\fP"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinitial\fP The initial value the value should take 
.RE
.PP

.PP
Definition at line 31 of file threadSafeT\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> T \fButility::ThreadSafeT\fP< T >::GetT ()\fC [inline]\fP"

.PP
Returns the internal T store\&. 
.PP
\fBReturns:\fP
.RS 4
The current value of T 
.RE
.PP

.PP
Definition at line 45 of file threadSafeT\&.h\&.
.SS "template<typename T> \fButility::ThreadSafeT\fP< T >::operator bool () const\fC [inline]\fP"

.PP
Implicit conversion operator for easier use in ifs\&. 
.PP
\fBReturns:\fP
.RS 4
The internally stored bool 
.RE
.PP

.PP
Definition at line 64 of file threadSafeT\&.h\&.
.SS "template<typename T> void \fButility::ThreadSafeT\fP< T >::SetT (T newVal)\fC [inline]\fP"

.PP
Sets the internal T variable\&. 
.PP
\fBParameters:\fP
.RS 4
\fInewVal\fP The new value that T should take 
.RE
.PP
\fBReturns:\fP
.RS 4
A reference to itself 
.RE
.PP

.PP
Definition at line 55 of file threadSafeT\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
