.TH "utility" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utility \- Defines a thread safe type\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Defines a thread safe type\&. 

Contains functions related to random string utility\&.
.PP
Contains functions related to random utility\&.
.PP
\fBAuthor:\fP
.RS 4
hmarcks
.RE
.PP
\fBDate:\fP
.RS 4
17/01/19
.RE
.PP
\fBTodo\fP
.RS 4
figure out why the overloads won't behave\&.\&.\&. 
.RE
.PP
.PP
\fBDate:\fP
.RS 4
10/28/18
.PP
10/28/18
.RE
.PP
\fBAuthor:\fP
.RS 4
hmarcks 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
