.TH "utility::EnumHandler< K, V >" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utility::EnumHandler< K, V > \- Maps enums\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <enumHandler\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnumHandler\fP ()=default"
.br
.RI "Default Constructor\&. "
.ti -1c
.RI "\fB~EnumHandler\fP ()=default"
.br
.RI "Default Destructor\&. "
.ti -1c
.RI "void \fBRegisterEnum\fP (K key, V value)"
.br
.RI "Registers an Enum to the internal map\&. "
.ti -1c
.RI "V \fBgetValue\fP (K key)"
.br
.RI "Looks up a value based on the key\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class K, class V>
.br
class utility::EnumHandler< K, V >"
Maps enums\&. 


.PP
\fBTemplate Parameters:\fP
.RS 4
\fIK\fP The key by which we want to look up values 
.br
\fIV\fP What we want to return 
.RE
.PP

.PP
Definition at line 24 of file enumHandler\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class K, class V> V \fButility::EnumHandler\fP< K, V >::getValue (K key)\fC [inline]\fP"

.PP
Looks up a value based on the key\&. 
.PP
\fBParameters:\fP
.RS 4
\fIkey\fP The key for the value we wish to look up 
.RE
.PP
\fBReturns:\fP
.RS 4
A copy of the stored value 
.RE
.PP

.PP
Definition at line 49 of file enumHandler\&.h\&.
.SS "template<class K, class V> void \fButility::EnumHandler\fP< K, V >::RegisterEnum (K key, V value)\fC [inline]\fP"

.PP
Registers an Enum to the internal map\&. 
.PP
\fBParameters:\fP
.RS 4
\fIkey\fP The key for the value 
.br
\fIvalue\fP The value described by the key 
.RE
.PP

.PP
Definition at line 40 of file enumHandler\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
