.TH "Worker" 3 "Wed Apr 3 2019" "Version 0.1" "Protocol Developer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Worker
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWorker\fP (unsigned N, float guess, unsigned iter)"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Functor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Protocol Developer from the source code\&.
