var modules =
[
    [ "HelloGoodByeServer", "d7/d93/group__HelloGoodByeServer.html", null ],
    [ "HelloWorldServer", "d2/d8a/group__helloWorldServer.html", null ],
    [ "Spikes", "d2/d2c/group__spikes.html", null ],
    [ "DUTTY", "d8/d05/group__DUTTY.html", null ],
    [ "CMocking", "d9/dbb/group__cMocking.html", null ],
    [ "CFunctions", "d5/d71/group__cFunctions.html", null ],
    [ "Library", "de/dab/group__NetworkCommunication.html", null ],
    [ "LibnetworkCommunication", "d9/d2e/group__libnetworkCommunication.html", null ],
    [ "LoggerClass", "dd/dc8/group__LoggerClass.html", null ],
    [ "LoggerClasses", "d6/d1f/group__LoggerClasses.html", null ],
    [ "Logger", "d6/d81/group__Logger.html", null ],
    [ "Logger", "dc/d55/group__logger.html", null ],
    [ "CommunicationHandler", "d0/d9b/group__CommunicationHandler.html", null ],
    [ "PluginLoader", "d4/d6e/group__PluginLoader.html", null ],
    [ "Loader", "da/d8e/group__Plugin.html", null ],
    [ "Protocol", "de/dca/group__Protocol.html", "de/dca/group__Protocol" ],
    [ "Hmarcks", "db/d10/group__hmarcks.html", null ],
    [ "Utility", "de/d15/group__Utility.html", null ],
    [ "TestAnalyser2", "db/dad/group__testAnalyser2.html", null ],
    [ "TestCaseHandler", "d7/dc7/group__testCaseHandler.html", null ],
    [ "TestCaseParser", "d1/d5b/group__testCaseParser.html", null ],
    [ "Runner", "d2/df3/group__Test.html", null ],
    [ "TestRunner", "d0/df6/group__TestRunner.html", null ],
    [ "Handler", "db/dfd/group__Thread.html", null ],
    [ "ThreadHandler", "de/de2/group__ThreadHandler.html", null ],
    [ "handler", "da/dd8/group__thread.html", null ],
    [ "TimeTicker", "dd/d8d/group__TimeTicker.html", null ],
    [ "Ticker", "d0/dd5/group__Time.html", null ],
    [ "TimeTicker", "d4/d95/group__timeTicker.html", null ],
    [ "TimeSpec", "d0/d4a/group__timeSpec.html", null ],
    [ "Utility", "d7/d6a/group__utility.html", null ]
];